# Copyright (c) 2010-2024, InterDigital
# All rights reserved. 
# See LICENSE under the root folder.

WEIGHTS_PATH:  "/home/rnf-pcac/weights"

model_configs:

  - id: "RNF_BP"
    arch_type: "BP"
    # Archi configs
    N_levels: [[3,12,24,96], [3,12,24,96], [3,12,24,96], [3,12,24,96], [3,12,24,96], [3,12,24,96], [3,12,24,96]]
    num_filters_M: [128,128,128,128,128,128,128]
    enh_channels: [64,64,64,64,64,64,64]
    attention_channels: [128,128,128,128,128,128,128]
    num_scales: [64,64,64,64,64,64,64]
    scale_max: [256.,256.,256.,256.,256.,256.,256.]
    scale_min: [.11,.11,.11,.11,.11,.11,.11]
    squeeze_type: ["avg","avg","avg","avg","avg","avg","avg"]

    lambda: [16000, 8000, 4000, 2000, 1000, 400, 100]
    color_space: ["YUV","YUV","YUV","YUV","YUV","YUV","YUV"]
    
    # train configurations
    train_dataset: [
                    "path_to_train_dataset1/",
                    "path_to_train_dataset2/",
                    ]
    validation_dataset: [
                         "path_to_validation_dataset1/",
                         "path_to_validation_dataset1/",
                         ]
    # Start training from previous calculated to speed up training
    load_weights: ["None",
                   "/home/rnf-pcac/weights/RNF_BP/1.60e+04/last_ckp.pth.tar",
                   "/home/rnf-pcac/weights/RNF_BP/8.00e+03/last_ckp.pth.tar",
                   "/home/rnf-pcac/weights/RNF_BP/4.00e+03/last_ckp.pth.tar",
                   "/home/rnf-pcac/weights/RNF_BP/2.00e+03/last_ckp.pth.tar",
                   "/home/rnf-pcac/weights/RNF_BP/1.00e+03/last_ckp.pth.tar",
                   "/home/rnf-pcac/weights/RNF_BP/4.00e+02/last_ckp.pth.tar"]
    batch_size: 8
    learning_rate: 1.0e-4
    epochs: [30,10,10,10,10,10,10]

  - id: "RNF_NA"
    arch_type: "NA"
    # Archi configs
    N_levels: [2,2,2,2,2,2,2]
    num_filters_M: [128,128,128,128,128,128,128]
    enh_channels: [64,64,64,64,64,64,64]
    attention_channels: [128,128,128,128,128,128,128]
    num_scales: [64,64,64,64,64,64,64]
    scale_max: [256.,256.,256.,256.,256.,256.,256.]
    scale_min: [.11,.11,.11,.11,.11,.11,.11]
    squeeze_type: ["avg","avg","avg","avg","avg","avg","avg"]

    lambda: [16000, 8000, 4000, 2000, 1000, 400, 100]
    color_space: ["YUV","YUV","YUV","YUV","YUV","YUV","YUV"]
    
    # train configurations
    train_dataset: [
                    "path_to_train_dataset1/",
                    "path_to_train_dataset2/",
                    ]
    validation_dataset: [
                         "path_to_validation_dataset1/",
                         "path_to_validation_dataset1/",
                         ]
    # Start training from previous calculated to speed up training
    load_weights: ["None",
                   "/home/rnf-pcac/weights/RNF_NA/1.60e+04/last_ckp.pth.tar",
                   "/home/rnf-pcac/weights/RNF_NA/8.00e+03/last_ckp.pth.tar",
                   "/home/rnf-pcac/weights/RNF_NA/4.00e+03/last_ckp.pth.tar",
                   "/home/rnf-pcac/weights/RNF_NA/2.00e+03/last_ckp.pth.tar",
                   "/home/rnf-pcac/weights/RNF_NA/1.00e+03/last_ckp.pth.tar",
                   "/home/rnf-pcac/weights/RNF_NA/4.00e+02/last_ckp.pth.tar"]
    batch_size: 8
    learning_rate: 1.0e-4
    epochs: [30,10,10,10,10,10,10]